from __future__ import annotations

"""
Helpers for calling DataForSEO Labs APIs for the SEO Agent.

Primary endpoints used:
- POST /v3/dataforseo_labs/google/ranked_keywords/live      → current visibility
- POST /v3/dataforseo_labs/google/domain_intersection/live  → keyword gap vs competitors
"""

from typing import Any, Dict, List, Optional

import logging
from datetime import datetime, timedelta, timezone
from urllib.parse import urlparse

import json
import math
import requests
from django.conf import settings

from .models import BusinessProfile, SEOOverviewSnapshot, OnPageAuditSnapshot
from .onpage_audit import run_onpage_audit_for_user

logger = logging.getLogger(__name__)

# Lazy import to avoid circular dependency (openai_utils imports get_or_refresh_seo_score_for_user)
def _get_llm_keyword_candidates(profile: Optional[BusinessProfile], homepage_meta: Optional[str]) -> List[str]:
    try:
        from .openai_utils import generate_seo_keyword_candidates
        return generate_seo_keyword_candidates(profile, homepage_meta)
    except Exception:
        logger.exception("[SEO score] LLM keyword generation failed")
        return []

BASE_URL = "https://api.dataforseo.com"
DEBUG_LOG_PATH = "debug-098bfd.log"

# Industries where broad local directories (Yelp, Angi, etc.) are relevant competitors.
# For other niches (e.g. SaaS, resume tools), we do not use these defaults.
_LOCAL_INDUSTRY_KEYWORDS = frozenset({
    "home services", "plumbing", "restaurant", "legal", "contractor",
    "cleaning", "landscaping", "roofing", "electrical", "hvac", "real estate",
})

# Seed keywords come only from the LLM (generate_seo_keyword_candidates) and are
# validated via DataForSEO search volume; no fixed industry/generic seed data.


# Stopwords: phrases must not start/end with these, and we do not form n-grams from them.
_DESC_STOPWORDS = frozenset({
    "the", "a", "an", "is", "are", "was", "were", "and", "or", "but",
    "in", "on", "at", "to", "for", "of", "with", "by", "as", "it", "its",
    "that", "this", "takes", "take", "while", "also", "from", "into",
    "user", "users", "their", "them", "they", "we", "our", "your",
})

# Verb/noun forms to normalize toward search-intent (verb -> noun or service term).
_DESC_NORMALIZE = {
    "tailors": "tailoring", "tailor": "tailoring", "tailored": "tailoring",
    "improving": "improvement", "improve": "improvement", "improves": "improvement",
    "optimizing": "optimization", "optimize": "optimization", "optimizes": "optimization",
    "building": "builder", "builds": "builder", "build": "builder",
    "checking": "checker", "checks": "checker", "check": "checker",
}

# Concept-style phrases (e.g. ATS resume checker, resume optimization tool) are generated by the LLM
# in generate_seo_keyword_candidates(); no fixed concept map is used here.


def _significant_words(text: str) -> List[str]:
    """Tokenize and return only words that are not stopwords and look substantive."""
    words = [w for w in text.split() if w.isalnum() or w.replace("-", "").isalnum()]
    out = []
    for w in words:
        low = w.lower()
        if low in _DESC_STOPWORDS:
            continue
        if len(low) >= 2 or low in ("ats", "ai", "cv"):
            out.append(w)
    return out


def _is_search_like(phrase: str, allow_one_stopword: bool = False) -> bool:
    """Reject fragments that do not resemble a natural search query."""
    if not phrase or len(phrase) < 4 or len(phrase) > 50:
        return False
    low = phrase.lower()
    words = low.split()
    if not words:
        return False
    if words[0] in _DESC_STOPWORDS or words[-1] in _DESC_STOPWORDS:
        return False
    stop_count = sum(1 for w in words if w in _DESC_STOPWORDS)
    if not allow_one_stopword and stop_count > 0:
        return False
    if allow_one_stopword and (stop_count > 1 or (stop_count == 1 and len(words) < 3)):
        return False  # allow at most one internal stopword in 3+ word phrases (e.g. "resume for job description")
    if len(words) < 2:
        return False
    if any(frag in low for frag in (" that ", " that", " a ", " and ", " to the ", " it ")):
        return False
    return True


def _normalize_phrase(phrase: str) -> str:
    """Convert phrase toward search-intent form (e.g. 'resume tailors' -> 'resume tailoring')."""
    words = phrase.split()
    out = []
    for w in words:
        low = w.lower()
        out.append(_DESC_NORMALIZE.get(low, low))
    normalized = " ".join(out)
    # Prefer "ATS X" over "X ATS" for search intent (e.g. "improvement ATS" -> "ATS improvement")
    parts = normalized.split()
    if len(parts) == 2 and parts[1].lower() == "ats":
        normalized = f"{parts[1]} {parts[0]}"
    return normalized


def _extract_phrases_from_description(description: str, max_phrases: int = 5) -> List[str]:
    """
    Extract search-intent keyword phrases from business description using only
    significant-word consecutive n-grams. No fixed concept maps; concept-style
    phrases (e.g. ATS resume checker, resume optimization tool) come from the LLM.
    """
    if not description or not description.strip():
        return []
    text = description.strip()
    significant = _significant_words(text)
    if len(significant) < 2:
        return []

    seen: set = set()
    out: List[str] = []

    for n in (3, 2):
        for i in range(len(significant) - n + 1):
            if len(out) >= max_phrases + 5:
                break
            phrase_words = significant[i : i + n]
            raw = " ".join(phrase_words).strip()[:50]
            candidate = _normalize_phrase(raw)
            candidate = candidate.strip()[:50]
            if not _is_search_like(candidate):
                continue
            key = candidate.lower()
            if key in seen:
                continue
            seen.add(key)
            out.append(candidate)

    def score_phrase(s: str) -> tuple:
        w = s.split()
        return (len(w), -len(s), s.lower())

    out_sorted = sorted(set(out), key=score_phrase, reverse=True)
    return out_sorted[:max_phrases]


def _get_business_seed_phrases(user) -> List[tuple[str, int]]:
    """
    Build niche-specific seed keywords from BusinessProfile: industry, description,
    and business name. Returns list of (phrase, default_search_volume) so that
    top_keywords reflect what the business actually offers (e.g. resume builder,
    online resume creator) rather than generic terms.
    """
    profile = None
    try:
        profile = BusinessProfile.objects.filter(user=user).first()
    except Exception:
        return []
    if not profile:
        return []

    seeds: List[tuple[str, int]] = []
    industry = (profile.industry or "").strip()
    description = (profile.description or "").strip()
    business_name = (profile.business_name or "").strip()

    if industry and len(industry) >= 2 and len(industry) <= 60:
        seeds.append((industry, 500))

    for phrase in _extract_phrases_from_description(description, max_phrases=5):
        if phrase and phrase not in {s[0] for s in seeds}:
            seeds.append((phrase, 400))

    # Only add business name if it's descriptive (e.g. "Oak Tree Plumbing"); skip single-word brands like "Rezzii"
    if business_name and len(business_name) >= 2 and len(business_name) <= 60:
        name_lower = business_name.lower()
        if name_lower not in {s[0].lower() for s in seeds}:
            words = business_name.split()
            if len(words) > 1 or len(business_name) > 8:
                seeds.append((business_name, 300))

    return seeds


def _get_auth() -> Optional[tuple[str, str]]:
    """
    Return (login, password) tuple for DataForSEO HTTP Basic auth.

    Expected settings or env:
    - DATAFORSEO_LOGIN
    - DATAFORSEO_PASSWORD
    """
    login = getattr(settings, "DATAFORSEO_LOGIN", None)
    password = getattr(settings, "DATAFORSEO_PASSWORD", None)

    if not login or not password:
        logger.warning(
            "[DataForSEO] Missing DATAFORSEO_LOGIN/DATAFORSEO_PASSWORD; skipping API call.",
        )
        return None
    return str(login), str(password)


def _get_search_volumes_for_keywords(
    keywords: List[str],
    location_code: int,
) -> Dict[str, int]:
    """
    Fetch monthly search volume for a list of keyword phrases via DataForSEO
    keywords_data/google/search_volume/live. Returns a dict keyed by keyword (lowercase)
    with search_volume > 0 only. Used to validate LLM-generated candidates.
    """
    if not keywords:
        return {}
    # DataForSEO recommends not sending language_code for this endpoint (can return null)
    payload = [
        {
            "location_code": int(location_code),
            "keywords": [str(k).strip() for k in keywords if str(k).strip()][:700],
        },
    ]
    data = _post("/v3/keywords_data/google/search_volume/live", payload)
    if not data:
        return {}
    result: Dict[str, int] = {}
    try:
        tasks = data.get("tasks") or []
        if not tasks:
            return {}
        for task in tasks:
            for item in task.get("result") or []:
                kw = (item.get("keyword") or "").strip()
                if not kw:
                    continue
                sv = item.get("search_volume")
                try:
                    vol = int(sv) if sv is not None else 0
                except (TypeError, ValueError):
                    vol = 0
                if vol > 0:
                    result[kw.lower()] = vol
        return result
    except Exception:
        logger.exception(
            "[DataForSEO] Error parsing search_volume/live response for keywords_count=%s",
            len(keywords),
        )
        return {}


def _post(path: str, payload: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    """Low-level POST helper with basic error handling."""
    auth = _get_auth()
    if auth is None:
        return None

    url = f"{BASE_URL}{path}"
    try:
        resp = requests.post(
            url,
            json=payload,
            auth=auth,
            timeout=30,
        )
    except Exception as exc:  # pragma: no cover - network failure
        logger.exception("[DataForSEO] POST %s failed: %s", path, exc)
        # #region agent log
        try:
            with open(DEBUG_LOG_PATH, "a") as f:
                f.write(json.dumps({
                    "sessionId": "098bfd",
                    "runId": "pre-fix",
                    "hypothesisId": "H1",
                    "location": "accounts/dataforseo_utils.py:_post",
                    "message": "HTTP error when calling DataForSEO",
                    "data": {"path": path, "error": str(exc)},
                    "timestamp": int(datetime.now(timezone.utc).timestamp() * 1000),
                }) + "\n")
        except Exception:
            pass
        # #endregion
        return None

    if resp.status_code != 200:
        # DataForSEO returns 200 with status_code inside body for logical errors;
        # non-200 here is a transport-level issue.
        logger.warning(
            "[DataForSEO] POST %s HTTP %s: %s",
            path,
            resp.status_code,
            resp.text[:500],
        )
        # #region agent log
        try:
            with open(DEBUG_LOG_PATH, "a") as f:
                f.write(json.dumps({
                    "sessionId": "098bfd",
                    "runId": "pre-fix",
                    "hypothesisId": "H1",
                    "location": "accounts/dataforseo_utils.py:_post",
                    "message": "Non-200 from DataForSEO",
                    "data": {
                        "path": path,
                        "status_code": resp.status_code,
                        "body_preview": resp.text[:200],
                    },
                    "timestamp": int(datetime.now(timezone.utc).timestamp() * 1000),
                }) + "\n")
        except Exception:
            pass
        # #endregion
        return None

    try:
        data = resp.json()
    except ValueError:  # pragma: no cover - unexpected non-JSON
        logger.warning("[DataForSEO] POST %s returned non-JSON body.", path)
        # #region agent log
        try:
            with open(DEBUG_LOG_PATH, "a") as f:
                f.write(json.dumps({
                    "sessionId": "098bfd",
                    "runId": "pre-fix",
                    "hypothesisId": "H1",
                    "location": "accounts/dataforseo_utils.py:_post",
                    "message": "Non-JSON response from DataForSEO",
                    "data": {"path": path, "body_preview": resp.text[:200]},
                    "timestamp": int(datetime.now(timezone.utc).timestamp() * 1000),
                }) + "\n")
        except Exception:
            pass
        # #endregion
        return None

    # DataForSEO wraps results in tasks / result; callers will unpack further.
    # #region agent log
    try:
        with open(DEBUG_LOG_PATH, "a") as f:
            f.write(json.dumps({
                "sessionId": "098bfd",
                "runId": "pre-fix",
                "hypothesisId": "H1",
                "location": "accounts/dataforseo_utils.py:_post",
                "message": "DataForSEO response summary",
                "data": {
                    "path": path,
                    "has_tasks": bool((data or {}).get("tasks")),
                },
                "timestamp": int(datetime.now(timezone.utc).timestamp() * 1000),
            }) + "\n")
    except Exception:
        pass
    # #endregion
    return data


def _ctr_for_position(position: int) -> float:
    """
    Simple CTR curve approximating typical SERP click-through rates.
    Position 1 ≈ 0.28, 2 ≈ 0.15, 3 ≈ 0.10, 4 ≈ 0.07, 5 ≈ 0.05, 6–10 decreasing.
    """
    if position <= 0:
        return 0.0
    if position == 1:
        return 0.28
    if position == 2:
        return 0.15
    if position == 3:
        return 0.10
    if position == 4:
        return 0.07
    if position == 5:
        return 0.05
    if 6 <= position <= 10:
        # Linearly decay from 0.04 at 6 → 0.01 at 10
        return max(0.01, 0.04 - (position - 6) * 0.0075)
    if 11 <= position <= 20:
        return 0.005
    return 0.002


def _extract_keyword_difficulty(keyword_info: Dict[str, Any]) -> Optional[float]:
    """
    Extract a difficulty / competition score from DataForSEO keyword_info.
    Handles either 0–1 or 0–100 scales and normalises to 0–100.
    """
    if not keyword_info:
        return None

    for key in ("competition", "competition_level", "difficulty", "keyword_difficulty"):
        if key in keyword_info and keyword_info[key] is not None:
            try:
                val = float(keyword_info[key])
            except (TypeError, ValueError):
                continue
            # If looks like 0–1, scale to 0–100
            if 0.0 <= val <= 1.0:
                return val * 100.0
            return max(0.0, min(100.0, val))

    return None


def _get_competitor_average_traffic(
    target_domain: str,
    *,
    location_code: int,
    language_code: str,
) -> float:
    """
    Call competitors_domain/live to estimate the average organic traffic/visibility
    of the top competitors for the given domain.
    """
    payload = [
        {
            "target": target_domain,
            "location_code": int(location_code),
            "language_code": language_code,
        },
    ]

    data = _post("/v3/dataforseo_labs/google/competitors_domain/live", payload)
    if not data:
        return 0.0

    try:
        tasks = data.get("tasks") or []
        if not tasks:
            return 0.0
        task = tasks[0]
        results = task.get("result") or []
        if not results:
            return 0.0
        result = results[0]
        items = result.get("items") or []
        if not items:
            return 0.0

        competitor_scores: List[float] = []
        for item in items:
            metrics = item.get("organic_metrics") or item
            raw_vis = (
                metrics.get("estimated_traffic")
                or metrics.get("visibility")
                or metrics.get("sum_search_volume")
                or 0
            )
            try:
                vis = float(raw_vis)
            except (TypeError, ValueError):
                vis = 0.0
            if vis > 0:
                competitor_scores.append(vis)

        if not competitor_scores:
            return 0.0

        return sum(competitor_scores) / len(competitor_scores)
    except Exception:
        logger.exception(
            "[DataForSEO] competitors_domain parsing failed for target_domain=%s",
            target_domain,
        )
        return 0.0


def _get_competitor_domains(
    target_domain: str,
    *,
    location_code: int,
    language_code: str,
    limit: int = 5,
) -> List[str]:
    """
    Call competitors_domain/live and return 3–5 main competitor domain names
    (excluding the target). Used to feed get_keyword_gap_keywords for
    high-intent opportunity keywords.
    """
    payload = [
        {
            "target": target_domain,
            "location_code": int(location_code),
            "language_code": language_code,
            "limit": min(limit + 5, 100),
        },
    ]
    data = _post("/v3/dataforseo_labs/google/competitors_domain/live", payload)
    if not data:
        return []

    try:
        tasks = data.get("tasks") or []
        if not tasks:
            return []
        task = tasks[0]
        results = task.get("result") or []
        if not results:
            return []
        result = results[0]
        items = result.get("items") or []
        target_lower = target_domain.lower().strip()
        domains: List[str] = []
        for item in items:
            domain = (item.get("domain") or "").strip().lower()
            if not domain or domain == target_lower:
                continue
            if domain in domains:
                continue
            domains.append(domain)
            if len(domains) >= limit:
                break
        logger.info(
            "[DataForSEO] competitors_domain domains for target=%s -> %s",
            target_domain,
            domains[:limit],
        )
        return domains[:limit]
    except Exception:
        logger.exception(
            "[DataForSEO] competitors_domain domain list parsing failed for target_domain=%s",
            target_domain,
        )
        return []


def get_ranked_keywords_visibility(
    target_domain: str,
    *,
    location_code: int,
    language_code: str = "en",
    limit: int = 100,
) -> Optional[Dict[str, Any]]:
    """
    Call ranked_keywords/live to get visibility & ranking metrics for a domain.

    Returns a dict with at least:
    - visibility: float
    - keywords_count: int
    - top3_positions: int
    """
    # #region agent log
    from . import debug_log as _debug
    _debug.log("dataforseo_utils.py:get_ranked_keywords_visibility:entry", "DataForSEO call", {"target_domain": target_domain, "location_code": location_code}, "H3")
    # #endregion
    payload = [
        {
            "target": target_domain,
            "location_code": int(location_code),
            "language_code": language_code,
            "limit": int(limit),
        },
    ]

    data = _post("/v3/dataforseo_labs/google/ranked_keywords/live", payload)
    # #region agent log
    _debug.log("dataforseo_utils.py:get_ranked_keywords_visibility:after_post", "API response", {"has_data": data is not None}, "H4")
    # #endregion
    if not data:
        return None

    try:
        tasks = data.get("tasks") or []
        if not tasks:
            # #region agent log
            _debug.log("dataforseo_utils.py:get_ranked_keywords_visibility:no_tasks", "no tasks in response", {"target_domain": target_domain}, "H5")
            # #endregion
            logger.warning("[DataForSEO] ranked_keywords: no tasks in response for %s", target_domain)
            return None
        task = tasks[0]
        results = task.get("result") or []
        if not results:
            # #region agent log
            _debug.log("dataforseo_utils.py:get_ranked_keywords_visibility:no_result", "no result for domain", {"target_domain": target_domain}, "H5")
            # #endregion
            logger.warning("[DataForSEO] ranked_keywords: no result for %s", target_domain)
            return None
        result = results[0]
        items = result.get("items") or []

        keywords_count = len(items)

        top3 = sum(
            1 for item in items
            if item.get("rank_absolute") and item["rank_absolute"] <= 3
        )

        # crude visibility proxy
        visibility = sum(
            (item.get("search_volume") or 0)
            for item in items
        )

        logger.info(
            "[DataForSEO] ranked_keywords target=%s visibility=%.2f keywords_count=%s top3=%s",
            target_domain,
            visibility,
            keywords_count,
            top3,
        )

        # #region agent log
        _debug.log("dataforseo_utils.py:get_ranked_keywords_visibility:success", "returning visibility dict", {"keywords_count": keywords_count, "top3_positions": top3}, "H5")
        # #endregion
        return {
            "visibility": visibility,
            "keywords_count": keywords_count,
            "top3_positions": top3,
        }
    except Exception as exc:  # pragma: no cover - defensive
        # #region agent log
        _debug.log("dataforseo_utils.py:get_ranked_keywords_visibility:exception", "parsing exception", {"exc_type": type(exc).__name__, "exc_msg": str(exc)[:200]}, "H4")
        # #endregion
        logger.exception(
            "[DataForSEO] ranked_keywords parsing failed for %s: %s",
            target_domain,
            exc,
        )
        return None


def get_keyword_gap_keywords(
    target_domain: str,
    competitor_domains: List[str],
    *,
    location_code: int,
    language_code: str = "en",
    limit: int = 100,
) -> List[Dict[str, Any]]:
    """
    Call domain_intersection/live to compute keyword gaps vs competitors.

    For now we return a simplified list of items suitable for the frontend SEO keywords table:
    - keyword
    - search_volume
    """
    cleaned_competitors = [c.strip().lower() for c in competitor_domains if c.strip()]
    if not cleaned_competitors:
        logger.info(
            "[DataForSEO] domain_intersection skipped for %s: no competitors configured",
            target_domain,
        )
        return []

    # The domain_intersection endpoint expects target1/target2 rather than a
    # "targets" array. Call it once per competitor and merge the results.
    # We also collect a short list of competitor URLs that are currently
    # ranking for each keyword so the frontend can show where competitors
    # dominate the SERP.
    aggregated: Dict[str, Dict[str, Any]] = {}

    for competitor in cleaned_competitors:
        payload = [
            {
                "target1": target_domain,
                "target2": competitor,
                "location_code": int(location_code),
                "language_code": language_code,
                # intersections=true ensures we only get queries where both
                # domains have ranking URLs in the SERP.
                "intersections": True,
                "limit": int(limit),
            },
        ]

        data = _post("/v3/dataforseo_labs/google/domain_intersection/live", payload)
        if not data:
            continue
        try:
            tasks = data.get("tasks") or []
            if not tasks:
                logger.warning(
                    "[DataForSEO] domain_intersection: no tasks in response for %s vs %s",
                    target_domain,
                    competitor,
                )
                continue

            for task in tasks:
                results = task.get("result") or []
                if not results:
                    logger.warning(
                        "[DataForSEO] domain_intersection: no result for %s vs %s",
                        target_domain,
                        competitor,
                    )
                    continue

                for result in results:
                    items = result.get("items") or []
                    for item in items:
                        keyword_data = item.get("keyword_data") or {}
                        kw = keyword_data.get("keyword") or item.get("keyword")
                        if not kw:
                            continue

                        keyword_info = keyword_data.get("keyword_info") or {}
                        search_volume = (
                            keyword_info.get("search_volume")
                            or keyword_info.get("search_volume_global")
                            or keyword_info.get("sum_search_volume")
                            or item.get("search_volume")
                            or item.get("sum_search_volume")
                        )

                        # For each keyword, keep track of competitor URLs and
                        # ranks for the competitor side of the intersection.
                        serp_el = item.get("second_domain_serp_element") or item.get("first_domain_serp_element") or {}
                        comp_domain = (
                            serp_el.get("main_domain")
                            or serp_el.get("domain")
                            or competitor
                        )
                        comp_url = serp_el.get("url") or ""
                        comp_rank = serp_el.get("rank_absolute")

                        existing = aggregated.get(kw)
                        if existing is None:
                            competitors_list: List[Dict[str, Any]] = []
                            if comp_url:
                                competitors_list.append(
                                    {
                                        "domain": comp_domain,
                                        "url": comp_url,
                                        "rank": comp_rank,
                                    },
                                )
                            aggregated[kw] = {
                                "keyword": kw,
                                "search_volume": search_volume,
                                "competitors": competitors_list,
                            }
                        else:
                            # Keep the highest search volume we have seen.
                            prev_sv = existing.get("search_volume") or 0
                            curr_sv = search_volume or 0
                            if curr_sv > prev_sv:
                                existing["search_volume"] = search_volume

                            # Merge competitor URLs, keeping at most 3 per keyword,
                            # preferring better (lower) ranks.
                            if comp_url:
                                comp_entry = {
                                    "domain": comp_domain,
                                    "url": comp_url,
                                    "rank": comp_rank,
                                }
                                existing_list: List[Dict[str, Any]] = existing.setdefault("competitors", [])

                                # Avoid exact duplicates (same domain + URL).
                                if not any(
                                    c.get("domain") == comp_entry["domain"] and c.get("url") == comp_entry["url"]
                                    for c in existing_list
                                ):
                                    existing_list.append(comp_entry)

                                # Keep only top 3 by rank (ascending), with None ranks sorted last.
                                existing_list.sort(
                                    key=lambda c: (c.get("rank") or 10_000_000),
                                )
                                if len(existing_list) > 3:
                                    del existing_list[3:]

        except Exception as exc:  # pragma: no cover - defensive
            logger.exception(
                "[DataForSEO] domain_intersection parsing failed for %s vs %s: %s",
                target_domain,
                competitor,
                exc,
            )
            continue

    gap_keywords = list(aggregated.values())

    logger.info(
        "[DataForSEO] domain_intersection target=%s competitors=%s keyword_count=%s",
        target_domain,
        ",".join(cleaned_competitors),
        len(gap_keywords),
    )
    return gap_keywords


def compute_professional_seo_score(
    *,
    estimated_traffic: float,
    keywords_count: int,
    top3_positions: int,
    top10_positions: int,
    avg_keyword_difficulty: Optional[float],
    competitor_avg_traffic: float,
) -> int:
    """
    Collapse core SEO metrics into a single 0–100 "professional grade" score using:
    - estimated organic traffic (via CTR curve)
    - keyword breadth
    - ranking quality (share in top 3 / top 10)
    - keyword difficulty strength
    - competitive market share vs. top competitors

    All components are soft-scaled so smaller sites can still make meaningful progress.
    """
    try:
        traffic = max(float(estimated_traffic), 0.0)
        k = max(int(keywords_count), 0)
        t = max(int(top3_positions), 0)
        t10 = max(int(top10_positions), 0)
    except (TypeError, ValueError):
        traffic, k, t, t10 = 0.0, 0, 0, 0

    import math

    # 1) Traffic visibility: log-scaled estimated organic traffic.
    # 0 → 0, 100 → ~30, 1k → ~55, 10k → ~75, 100k → ~90, 1M+ → ~100
    if traffic <= 0:
        visibility_score = 0.0
    else:
        visibility_score = min(100.0, (math.log10(traffic + 10.0) / 6.0) * 100.0)

    # 2) Keyword breadth: log-scaled number of ranking keywords.
    # 1 → ~15, 10 → ~35, 100 → ~60, 1k → ~85, 10k → ~100
    if k <= 0:
        breadth_score = 0.0
    else:
        breadth_score = min(100.0, (math.log10(k + 1.0) / 4.0) * 100.0)

    # 3) Ranking quality: combination of share in top 3 and share in top 10.
    if k <= 0:
        ranking_score = 0.0
    else:
        top3_share = min(t / k, 1.0)
        top10_share = min(t10 / k, 1.0)
        ranking_score = (top3_share * 0.7 + top10_share * 0.3) * 100.0

    # 4) Keyword difficulty strength: reward sites ranking on harder keywords.
    # We treat difficulty as 0–100 where higher means more competitive queries.
    if avg_keyword_difficulty is None:
        difficulty_score = 0.0
    else:
        d = max(0.0, min(100.0, float(avg_keyword_difficulty)))
        # Slightly compress extremes so very hard portfolios don't instantly max out.
        difficulty_score = 10.0 + (d * 0.8)
        difficulty_score = max(0.0, min(100.0, difficulty_score))

    # 5) Competitive market share: share of traffic vs. average competitor.
    if traffic <= 0 or competitor_avg_traffic <= 0:
        market_share_score = 0.0
    else:
        # ratio > 1 means above-average vs. top competitors.
        ratio = traffic / max(competitor_avg_traffic, 1e-6)
        # Soft saturation: 0.5 → ~33, 1 → ~66, 2 → ~85, 3+ → ~95
        market_share_score = min(
            95.0,
            (math.log10(ratio + 1.0) / math.log10(4.0)) * 100.0,
        )

    # Weighted blend:
    # - visibility: 40%
    # - breadth: 20%
    # - ranking quality: 15%
    # - keyword difficulty: 15%
    # - competitive strength: 10%
    final = (
        visibility_score * 0.40
        + breadth_score * 0.20
        + ranking_score * 0.15
        + difficulty_score * 0.15
        + market_share_score * 0.10
    )

    return max(0, min(100, int(round(final))))


def get_or_refresh_seo_score_for_user(
    user,
    *,
    site_url: str | None,
) -> Dict[str, Any] | None:
    """
    Fetch a cached, professional-grade SEO score + core metrics for the given user,
    refreshing from DataForSEO at most once per hour (same cadence as the dashboard)
    and combining:
    - Search Performance (ranked_keywords + competitors)
    - On-Page SEO (metadata, headings, alt text)
    - Technical SEO (links, canonical, robots, sitemap)

    Returns a dict with at least:
    - seo_score (Overall SEO Score 0–100)
    - search_performance_score
    - onpage_seo_score
    - technical_seo_score
    - organic_visitors (estimated traffic)
    - keywords_ranking
    - top3_positions
    or None if no website is configured / domain cannot be derived.
    """
    today = datetime.now(timezone.utc).date()
    start_current = today.replace(day=1)
    if not site_url:
        # #region agent log
        try:
            with open(DEBUG_LOG_PATH, "a") as f:
                f.write(json.dumps({
                    "sessionId": "098bfd",
                    "runId": "pre-fix",
                    "hypothesisId": "H2",
                    "location": "accounts/dataforseo_utils.py:get_or_refresh_seo_score_for_user",
                    "message": "No site_url; skipping SEO score calculation",
                    "data": {"user_id": getattr(user, "id", None)},
                    "timestamp": int(datetime.now(timezone.utc).timestamp() * 1000),
                }) + "\n")
        except Exception:
            pass
        # #endregion
        return None

    parsed = urlparse(site_url)
    domain = (parsed.netloc or parsed.path or "").lower()
    if domain.startswith("www."):
        domain = domain[4:]
    if not domain:
        # #region agent log
        try:
            with open(DEBUG_LOG_PATH, "a") as f:
                f.write(json.dumps({
                    "sessionId": "098bfd",
                    "runId": "pre-fix",
                    "hypothesisId": "H2",
                    "location": "accounts/dataforseo_utils.py:get_or_refresh_seo_score_for_user",
                    "message": "Could not normalise domain from site_url",
                    "data": {"user_id": getattr(user, "id", None), "site_url": site_url},
                    "timestamp": int(datetime.now(timezone.utc).timestamp() * 1000),
                }) + "\n")
        except Exception:
            pass
        # #endregion
        return None

    # Return cached keyword and search metrics if refreshed within the last hour and domain unchanged
    now_utc = datetime.now(timezone.utc)
    cache_ttl = timedelta(hours=1)
    try:
        snapshot = SEOOverviewSnapshot.objects.filter(
            user=user,
            period_start=start_current,
        ).first()
        if snapshot and snapshot.refreshed_at and snapshot.cached_domain:
            age = now_utc - snapshot.refreshed_at
            if age <= cache_ttl and (snapshot.cached_domain or "").strip().lower() == domain:
                # Use cached keywords and search metrics; still attach current on-page/technical
                onpage_snapshot = run_onpage_audit_for_user(user, site_url)
                onpage_score = onpage_snapshot.onpage_seo_score if onpage_snapshot else 0
                technical_score = onpage_snapshot.technical_seo_score if onpage_snapshot else 0
                pages_audited = onpage_snapshot.pages_audited if onpage_snapshot else 0
                onpage_issue_summaries = onpage_snapshot.issue_summaries if onpage_snapshot else {}
                search_perf = snapshot.search_performance_score
                if search_perf is None:
                    search_perf = 0
                overall = int(round(
                    search_perf * 0.5 + onpage_score * 0.3 + technical_score * 0.2
                ))
                return {
                    "seo_score": overall,
                    "search_performance_score": search_perf,
                    "onpage_seo_score": onpage_score,
                    "technical_seo_score": technical_score,
                    "pages_audited": pages_audited,
                    "onpage_issue_summaries": onpage_issue_summaries,
                    "organic_visitors": snapshot.organic_visitors,
                    "total_search_volume": getattr(snapshot, "total_search_volume", 0) or 0,
                    "keywords_ranking": snapshot.keywords_ranking,
                    "top3_positions": snapshot.top3_positions,
                    "search_visibility_percent": getattr(snapshot, "search_visibility_percent", 0) or 0,
                    "missed_searches_monthly": getattr(snapshot, "missed_searches_monthly", 0) or 0,
                    "top_keywords": getattr(snapshot, "top_keywords", None) or [],
                    "seo_next_steps": getattr(snapshot, "seo_next_steps", None) or [],
                }
    except Exception:
        logger.exception("[SEO score] Error reading keyword cache for user_id=%s", getattr(user, "id", None))

    location_code = int(getattr(settings, "DATAFORSEO_LOCATION_CODE", 2840))
    language_code = getattr(settings, "DATAFORSEO_LANGUAGE_CODE", "en")

    # Call ranked_keywords/live with richer parsing for the scoring algorithm.
    payload = [
        {
            "target": domain,
            "location_code": int(location_code),
            "language_code": language_code,
            "limit": 100,
        },
    ]

    logger.info(
        "[SEO score] ranked_keywords request user_id=%s domain=%s payload=%s",
        getattr(user, "id", None),
        domain,
        payload,
    )
    ranked_data = _post("/v3/dataforseo_labs/google/ranked_keywords/live", payload)
    if not ranked_data:
        logger.warning(
            "[SEO score] ranked_keywords returned no data for user_id=%s domain=%s",
            getattr(user, "id", None),
            domain,
        )
        seo_score = compute_professional_seo_score(
            estimated_traffic=0.0,
            keywords_count=0,
            top3_positions=0,
            top10_positions=0,
            avg_keyword_difficulty=None,
            competitor_avg_traffic=0.0,
        )
        # No search performance data; still try to attach on-page snapshot if available.
        search_performance_score = seo_score
        onpage_snapshot = run_onpage_audit_for_user(user, site_url)
        onpage_score = onpage_snapshot.onpage_seo_score if onpage_snapshot else 0
        technical_score = onpage_snapshot.technical_seo_score if onpage_snapshot else 0
        overall = int(round(
            search_performance_score * 0.5
            + onpage_score * 0.3
            + technical_score * 0.2
        ))
        # #region agent log
        try:
            with open(DEBUG_LOG_PATH, "a") as f:
                f.write(json.dumps({
                    "sessionId": "098bfd",
                    "runId": "pre-fix",
                    "hypothesisId": "H3",
                    "location": "accounts/dataforseo_utils.py:get_or_refresh_seo_score_for_user",
                    "message": "No ranked_data; using fallback SEO score",
                    "data": {"user_id": getattr(user, "id", None), "domain": domain, "seo_score": seo_score},
                    "timestamp": int(datetime.now(timezone.utc).timestamp() * 1000),
                }) + "\n")
        except Exception:
            pass
        # #endregion
        return {
            "seo_score": overall,
            "search_performance_score": search_performance_score,
            "onpage_seo_score": onpage_score,
            "technical_seo_score": technical_score,
            "organic_visitors": 0,
            "total_search_volume": 0,
            "keywords_ranking": 0,
            "top3_positions": 0,
            "search_visibility_percent": 0,
            "missed_searches_monthly": 0,
            "top_keywords": [],
            "seo_next_steps": [],
        }

    try:
        tasks = ranked_data.get("tasks") or []
        if not tasks:
            raise ValueError("no tasks")
        task = tasks[0]
        results = task.get("result") or []
        if not results:
            raise ValueError("no results")
        result = results[0]
        items = result.get("items") or []
        logger.info(
            "[SEO score] ranked_keywords parsed user_id=%s domain=%s task_status=%s items=%s",
            getattr(user, "id", None),
            domain,
            task.get("status_code"),
            len(items),
        )
        # Log a small preview of the first item for debugging (no PII or secrets).
        if items:
            preview = {
                "rank_absolute": items[0].get("rank_absolute"),
                "search_volume": (
                    ((items[0].get("keyword_data") or {}).get("keyword_info") or {}).get("search_volume")
                    or items[0].get("search_volume")
                ),
                "keyword": (items[0].get("keyword_data") or {}).get("keyword") or items[0].get("keyword"),
            }
            logger.info(
                "[SEO score] ranked_keywords first_item_preview user_id=%s domain=%s preview=%s",
                getattr(user, "id", None),
                domain,
                preview,
            )
    except Exception as exc:
        items = []
        logger.exception(
            "[SEO score] Error parsing ranked_keywords for user_id=%s domain=%s raw_preview=%s",
            getattr(user, "id", None),
            domain,
            str(ranked_data)[:200],
        )

    if not items:
        seo_score = compute_professional_seo_score(
            estimated_traffic=0.0,
            keywords_count=0,
            top3_positions=0,
            top10_positions=0,
            avg_keyword_difficulty=None,
            competitor_avg_traffic=0.0,
        )
        search_performance_score = seo_score
        onpage_snapshot = run_onpage_audit_for_user(user, site_url)
        onpage_score = onpage_snapshot.onpage_seo_score if onpage_snapshot else 0
        technical_score = onpage_snapshot.technical_seo_score if onpage_snapshot else 0
        overall = int(round(
            search_performance_score * 0.5
            + onpage_score * 0.3
            + technical_score * 0.2
        ))
        return {
            "seo_score": overall,
            "search_performance_score": search_performance_score,
            "onpage_seo_score": onpage_score,
            "technical_seo_score": technical_score,
            "organic_visitors": 0,
            "total_search_volume": 0,
            "keywords_ranking": 0,
            "top3_positions": 0,
            "search_visibility_percent": 0,
            "missed_searches_monthly": 0,
        }

    # Derive metrics from ranked keyword items.
    estimated_traffic = 0.0
    keywords_ranking = len(items)
    top3_positions = 0
    top10_positions = 0
    difficulties: List[float] = []
    total_search_volume = 0.0
    total_traffic_share = 0.0
    missed_searches_volume = 0.0
    MIN_SEARCH_VOLUME = 10
    top_keywords: List[Dict[str, Any]] = []

    for item in items:
        rank = item.get("rank_absolute") or item.get("rank_group")
        try:
            rank_int = int(rank) if rank is not None else None
        except (TypeError, ValueError):
            rank_int = None

        keyword_data = item.get("keyword_data") or {}
        kw_info = keyword_data.get("keyword_info") or {}
        search_volume = (
            kw_info.get("search_volume")
            or kw_info.get("search_volume_global")
            or kw_info.get("sum_search_volume")
            or item.get("search_volume")
            or item.get("sum_search_volume")
            or 0
        )
        try:
            sv = float(search_volume)
        except (TypeError, ValueError):
            sv = 0.0

        if sv > 0:
            total_search_volume += sv

        keyword_text = keyword_data.get("keyword") or item.get("keyword")
        if keyword_text and sv > 0:
            if rank_int is not None and rank_int > 0:
                # Existing ranked keyword — include as a concrete visibility signal.
                top_keywords.append(
                    {
                        "keyword": str(keyword_text),
                        "search_volume": int(sv),
                        "rank": int(rank_int),
                    }
                )
            elif rank_int is None and sv >= MIN_SEARCH_VOLUME:
                # New / unranked keyword with meaningful volume — treat as opportunity.
                top_keywords.append(
                    {
                        "keyword": str(keyword_text),
                        "search_volume": int(sv),
                        "rank": None,
                    }
                )

        traffic_share_raw = item.get("traffic_share")
        try:
            traffic_share = float(traffic_share_raw) if traffic_share_raw is not None else 0.0
        except (TypeError, ValueError):
            traffic_share = 0.0
        if traffic_share > 0:
            total_traffic_share += traffic_share

        if rank_int is not None and rank_int > 0 and sv > 0:
            ctr = _ctr_for_position(rank_int)
            estimated_traffic += sv * ctr

            if rank_int <= 3:
                top3_positions += 1
            if rank_int <= 10:
                top10_positions += 1

        # Missed searches: keywords where we're effectively not capturing traffic yet:
        # - position is > 10, or no traffic_share, with sufficient volume.
        if (
            sv >= MIN_SEARCH_VOLUME
            and (rank_int is None or rank_int > 10 or traffic_share <= 0.0)
        ):
            missed_searches_volume += sv

        diff = _extract_keyword_difficulty(kw_info)
        if diff is not None:
            difficulties.append(diff)

    avg_difficulty = sum(difficulties) / len(difficulties) if difficulties else None

    # --- Identify 3–5 main competitors in the same niche (avoid broad local dirs for non-local businesses) ---
    competitor_domains = _get_competitor_domains(
        domain,
        location_code=location_code,
        language_code=language_code,
        limit=5,
    )
    try:
        _profile = BusinessProfile.objects.filter(user=user).first()
    except Exception:
        _profile = None
    industry_lower = ((_profile.industry or "").strip()).lower() if _profile else ""
    if not competitor_domains and industry_lower in _LOCAL_INDUSTRY_KEYWORDS:
        raw_competitors = getattr(
            settings,
            "DATAFORSEO_DEFAULT_COMPETITORS",
            "yelp.com,angi.com,thumbtack.com,homeadvisor.com",
        )
        competitor_domains = [c.strip() for c in str(raw_competitors).split(",") if c.strip()]

    existing_keys = {str(k.get("keyword", "")).lower() for k in top_keywords if k.get("keyword")}

    if competitor_domains:
        try:
            gap_items = get_keyword_gap_keywords(
                domain,
                competitor_domains,
                location_code=location_code,
                language_code=language_code,
                limit=50,
            )
            for item in gap_items:
                kw = item.get("keyword")
                if not kw:
                    continue
                key_lower = str(kw).lower()
                if key_lower in existing_keys:
                    continue
                sv_gap = item.get("search_volume") or 0
                try:
                    sv_gap_f = float(sv_gap)
                except (TypeError, ValueError):
                    sv_gap_f = 0.0
                if sv_gap_f <= 0:
                    continue
                top_keywords.append(
                    {
                        "keyword": str(kw),
                        "search_volume": int(sv_gap_f),
                        "rank": None,
                    }
                )
                existing_keys.add(key_lower)
        except Exception:
            logger.exception(
                "[SEO score] Error while enriching top_keywords with gap keywords for domain=%s",
                domain,
            )

    # --- Validated LLM-generated seed keywords (after ranked + gap; no fixed seed data) ---
    try:
        homepage_meta: Optional[str] = None
        try:
            if _profile and getattr(_profile, "website_url", None):
                pass  # Optional: fetch homepage title/meta for LLM context
        except Exception:
            pass
        llm_candidates = _get_llm_keyword_candidates(_profile, homepage_meta)

        filtered_candidates: List[str] = []
        for phrase in llm_candidates:
            p = (phrase or "").strip()[:50]
            if not p or p.lower() in existing_keys:
                continue
            if not _is_search_like(p, allow_one_stopword=True):
                continue
            filtered_candidates.append(p)

        if filtered_candidates:
            volumes = _get_search_volumes_for_keywords(filtered_candidates, location_code)
            for phrase in filtered_candidates:
                key_lower = phrase.lower()
                vol = volumes.get(key_lower, 0)
                if vol <= 0:
                    continue
                if key_lower in existing_keys:
                    continue
                top_keywords.append(
                    {"keyword": phrase, "search_volume": int(vol), "rank": None}
                )
                existing_keys.add(key_lower)
    except Exception:
        logger.exception(
            "[SEO score] Error while adding LLM seed keywords for user_id=%s",
            getattr(user, "id", None),
        )

    # Sort and keep a compact list of top keywords by volume for the UI.
    top_keywords_sorted = sorted(
        top_keywords,
        key=lambda x: x.get("search_volume", 0),
        reverse=True,
    )[:20]

    # Total search volume across the full keyword set (ranked + gap + seed) so missed_searches
    # and visibility reflect all opportunity keywords we show, not just the API-ranked set.
    total_search_volume = sum(k.get("search_volume", 0) for k in top_keywords_sorted)

    # Search visibility: (estimated_traffic / total_search_volume) * 100, capped 0–100%
    if total_search_volume > 0:
        search_visibility_percent = int(round(
            max(0.0, min(100.0, (estimated_traffic / total_search_volume) * 100.0))
        ))
    else:
        search_visibility_percent = 0

    # Missed searches = total_search_volume - estimated_traffic; includes volume from
    # gap and seed keywords (rank None or >10) so the number matches the keyword list.
    missed_searches_monthly = int(round(max(0.0, total_search_volume - estimated_traffic)))

    # Competitor baseline from competitors_domain/live
    competitor_avg_traffic = _get_competitor_average_traffic(
        domain,
        location_code=location_code,
        language_code=language_code,
    )

    search_performance_score = compute_professional_seo_score(
        estimated_traffic=estimated_traffic,
        keywords_count=keywords_ranking,
        top3_positions=top3_positions,
        top10_positions=top10_positions,
        avg_keyword_difficulty=avg_difficulty,
        competitor_avg_traffic=competitor_avg_traffic,
    )

    # Persist keyword list and search metrics so they are not repopulated on every request
    try:
        snapshot, _ = SEOOverviewSnapshot.objects.get_or_create(
            user=user,
            period_start=start_current,
        )
        snapshot.organic_visitors = int(round(estimated_traffic))
        snapshot.keywords_ranking = keywords_ranking
        snapshot.top3_positions = top3_positions
        snapshot.refreshed_at = now_utc
        snapshot.cached_domain = domain
        snapshot.top_keywords = top_keywords_sorted
        snapshot.total_search_volume = int(round(total_search_volume))
        snapshot.missed_searches_monthly = missed_searches_monthly
        snapshot.search_visibility_percent = search_visibility_percent
        snapshot.search_performance_score = int(round(search_performance_score))
        snapshot.save()
    except Exception:
        logger.exception("[SEO score] Failed to save keyword cache for user_id=%s", getattr(user, "id", None))

    # Attach On-Page / Technical SEO scores via OnPageAuditSnapshot
    onpage_snapshot = run_onpage_audit_for_user(user, site_url)
    onpage_score = onpage_snapshot.onpage_seo_score if onpage_snapshot else 0
    technical_score = onpage_snapshot.technical_seo_score if onpage_snapshot else 0
    pages_audited = onpage_snapshot.pages_audited if onpage_snapshot else 0
    onpage_issue_summaries = onpage_snapshot.issue_summaries if onpage_snapshot else {}

    overall = int(round(
        search_performance_score * 0.5
        + onpage_score * 0.3
        + technical_score * 0.2
    ))

    result = {
        "seo_score": overall,
        "search_performance_score": search_performance_score,
        "onpage_seo_score": onpage_score,
        "technical_seo_score": technical_score,
        "pages_audited": pages_audited,
        "onpage_issue_summaries": onpage_issue_summaries,
        "organic_visitors": int(round(estimated_traffic)),
        "total_search_volume": int(round(total_search_volume)),
        "keywords_ranking": keywords_ranking,
        "top3_positions": top3_positions,
        "search_visibility_percent": search_visibility_percent,
        "missed_searches_monthly": missed_searches_monthly,
        "top_keywords": top_keywords_sorted,
    }

    # Next steps: only regenerate at most once per week; otherwise reuse cached list
    steps_ttl = timedelta(days=7)
    snapshot_for_steps = SEOOverviewSnapshot.objects.filter(
        user=user,
        period_start=start_current,
    ).first()
    cached_steps = []
    if snapshot_for_steps and getattr(snapshot_for_steps, "seo_next_steps_refreshed_at", None):
        refreshed_at = snapshot_for_steps.seo_next_steps_refreshed_at
        if refreshed_at and (now_utc - refreshed_at) <= steps_ttl:
            cached_steps = getattr(snapshot_for_steps, "seo_next_steps", None) or []
    if cached_steps:
        result["seo_next_steps"] = cached_steps
    else:
        try:
            from .openai_utils import generate_seo_next_steps
            steps = generate_seo_next_steps(result)
            result["seo_next_steps"] = steps if steps else []
        except Exception:
            logger.exception("[SEO score] Failed to generate seo_next_steps for user_id=%s", getattr(user, "id", None))
            result["seo_next_steps"] = []
        try:
            snap, _ = SEOOverviewSnapshot.objects.get_or_create(
                user=user,
                period_start=start_current,
            )
            snap.seo_next_steps = result.get("seo_next_steps") or []
            snap.seo_next_steps_refreshed_at = now_utc
            snap.save(update_fields=["seo_next_steps", "seo_next_steps_refreshed_at"])
        except Exception:
            logger.exception("[SEO score] Failed to save seo_next_steps to snapshot for user_id=%s", getattr(user, "id", None))

    return result

