# Generated by Django 5.2.12 on 2026-03-04 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_googlesearchconsoleconnection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOOverviewSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('last_fetched_at', models.DateTimeField(auto_now=True)),
                ('organic_visitors', models.IntegerField(default=0)),
                ('prev_organic_visitors', models.IntegerField(default=0)),
                ('keywords_ranking', models.IntegerField(default=0)),
                ('top3_positions', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_overview_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SEO overview snapshot',
                'verbose_name_plural': 'SEO overview snapshots',
                'unique_together': {('user', 'period_start')},
            },
        ),
    ]
