# Generated by Django 5.2.12 on 2026-03-04 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seooverviewsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsKeywordIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('avg_monthly_searches', models.IntegerField(default=0)),
                ('competition', models.CharField(blank=True, max_length=32)),
                ('competition_index', models.IntegerField(default=0)),
                ('low_top_of_page_bid_micros', models.BigIntegerField(default=0)),
                ('high_top_of_page_bid_micros', models.BigIntegerField(default=0)),
                ('last_fetched_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_keyword_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Ads keyword idea',
                'verbose_name_plural': 'Google Ads keyword ideas',
                'unique_together': {('user', 'keyword')},
            },
        ),
    ]
