# Generated by Django 5.2.12 on 2026-04-06 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_aeoextractionsnapshot_brand_url_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThirdPartyApiErrorLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("dataforseo", "DataForSEO"),
                            ("openai", "OpenAI"),
                            ("gemini", "Google Gemini"),
                            ("perplexity", "Perplexity"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Endpoint or logical operation name (same convention as ThirdPartyApiRequestLog).",
                        max_length=512,
                    ),
                ),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "error_kind",
                    models.CharField(
                        choices=[
                            ("http_error", "HTTP error"),
                            ("timeout", "Timeout"),
                            ("connection_error", "Connection error"),
                            ("parse_error", "Parse error"),
                            ("validation_error", "Validation error"),
                            ("unknown_exception", "Unknown exception"),
                        ],
                        db_index=True,
                        default="unknown_exception",
                        max_length=32,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short summary (exception message or status-derived text).",
                        max_length=1024,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Truncated response body or extra context (no full prompts).",
                    ),
                ),
                (
                    "business_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="third_party_api_error_logs",
                        to="accounts.businessprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Third-party API error",
                "verbose_name_plural": "Third-party API errors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="thirdpartyapierrorlog",
            index=models.Index(fields=["provider", "created_at"], name="accounts_th_provide_83c158_idx"),
        ),
        migrations.AddIndex(
            model_name="thirdpartyapierrorlog",
            index=models.Index(fields=["business_profile", "created_at"], name="accounts_th_busines_97beca_idx"),
        ),
    ]
