# Generated by Django 5.2.12 on 2026-04-10 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_onboardingonpagecrawl_business_topics_compat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AEOCompetitorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeo_competitor_snapshots', to='accounts.businessprofile')),
                ('platform_scope', models.CharField(default='all', help_text='all | openai | gemini | perplexity (matches AEOResponseSnapshot.platform).', max_length=32)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('total_slots', models.IntegerField(default=0)),
                ('rows_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AEO competitor snapshot',
                'verbose_name_plural': 'AEO competitor snapshots',
            },
        ),
        migrations.AddIndex(
            model_name='aeocompetitorsnapshot',
            index=models.Index(fields=['profile', '-updated_at'], name='aeo_comp_prof_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='aeocompetitorsnapshot',
            index=models.Index(fields=['profile', 'platform_scope'], name='aeo_comp_prof_plat_idx'),
        ),
        migrations.AddConstraint(
            model_name='aeocompetitorsnapshot',
            constraint=models.UniqueConstraint(fields=('profile', 'platform_scope', 'window_start', 'window_end'), name='accounts_aeo_comp_snapshot_scope_uq'),
        ),
    ]
