# Generated by Django 5.2.12 on 2026-04-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0059_aeocompetitorsnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="stripe_cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="stripe_current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="stripe_price_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="stripe_subscription_status",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
