# Generated by Django 5.x migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0077_seooverviewsnapshot_business_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingonpagecrawl",
            name="ranked_keywords_fetch_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Legacy / not applicable"),
                    ("pending", "Pending background fetch"),
                    ("complete", "Complete"),
                ],
                default="",
                help_text="pending=background Labs fetch in flight; complete=done or skipped; empty=pre-async rows.",
                max_length=16,
            ),
        ),
    ]
